Meta VERSION="1" .
Job JOBID="job_201109051946_0001" JOBNAME="foobar\.jar" USER="madhatter" SUBMIT_TIME="1315245129461" JOBCONF="hdfs://localhost:9000/Users/madhatter/CDH3/hadoop-cache/mapred/staging/madhatter/\.staging/job_201109051946_0001/job\.xml" VIEW_JOB="*" MODIFY_JOB="*" JOB_QUEUE="default" .
Job JOBID="job_201109051946_0001" JOB_PRIORITY="NORMAL" .
Job JOBID="job_201109051946_0001" LAUNCH_TIME="1315245130159" TOTAL_MAPS="3" TOTAL_REDUCES="0" JOB_STATUS="PREP" .
Task TASKID="task_201109051946_0001_m_000004" TASK_TYPE="SETUP" START_TIME="1315245130287" SPLITS="" .
MapAttempt TASK_TYPE="SETUP" TASKID="task_201109051946_0001_m_000004" TASK_ATTEMPT_ID="attempt_201109051946_0001_m_000004_0" START_TIME="1315245133594" TRACKER_NAME="tracker_nothing:localhost/127\.0\.0\.1:49420" HTTP_PORT="50060" .
MapAttempt TASK_TYPE="SETUP" TASKID="task_201109051946_0001_m_000004" TASK_ATTEMPT_ID="attempt_201109051946_0001_m_000004_0" TASK_STATUS="SUCCESS" FINISH_TIME="1315245135312" HOSTNAME="/default-rack/nothing" STATE_STRING="setup" COUNTERS="{(FileSystemCounters)(FileSystemCounters)[(FILE_BYTES_WRITTEN)(FILE_BYTES_WRITTEN)(82264)]}{(org\.apache\.hadoop\.mapred\.Task$Counter)(Map-Reduce Framework)[(SPILLED_RECORDS)(Spilled Records)(0)]}" .
Task TASKID="task_201109051946_0001_m_000004" TASK_TYPE="SETUP" TASK_STATUS="SUCCESS" FINISH_TIME="1315245135344" COUNTERS="{(FileSystemCounters)(FileSystemCounters)[(FILE_BYTES_WRITTEN)(FILE_BYTES_WRITTEN)(82264)]}{(org\.apache\.hadoop\.mapred\.Task$Counter)(Map-Reduce Framework)[(SPILLED_RECORDS)(Spilled Records)(0)]}" .
Job JOBID="job_201109051946_0001" JOB_STATUS="RUNNING" .
Task TASKID="task_201109051946_0001_m_000000" TASK_TYPE="MAP" START_TIME="1315245135348" SPLITS="" .
Task TASKID="task_201109051946_0001_m_000001" TASK_TYPE="MAP" START_TIME="1315245135654" SPLITS="" .
MapAttempt TASK_TYPE="MAP" TASKID="task_201109051946_0001_m_000000" TASK_ATTEMPT_ID="attempt_201109051946_0001_m_000000_0" START_TIME="1315245135358" TRACKER_NAME="tracker_nothing:localhost/127\.0\.0\.1:49420" HTTP_PORT="50060" .
MapAttempt TASK_TYPE="MAP" TASKID="task_201109051946_0001_m_000000" TASK_ATTEMPT_ID="attempt_201109051946_0001_m_000000_0" TASK_STATUS="FAILED" FINISH_TIME="1315245143467" HOSTNAME="nothing" ERROR="java\.lang\.RuntimeException: Could not access HBase table foobar
	at com\.cloudera\.sqoop\.hbase\.HBasePutProcessor\.setConf(HBasePutProcessor\.java:97)
	at org\.apache\.hadoop\.util\.ReflectionUtils\.setConf(ReflectionUtils\.java:62)
	at org\.apache\.hadoop\.util\.ReflectionUtils\.newInstance(ReflectionUtils\.java:117)
	at com\.cloudera\.sqoop\.mapreduce\.DelegatingOutputFormat$DelegatingRecordWriter\.<init>(DelegatingOutputFormat\.java:109)
	at com\.cloudera\.sqoop\.mapreduce\.DelegatingOutputFormat\.getRecordWriter(DelegatingOutputFormat\.java:84)
	at org\.apache\.hadoop\.mapred\.MapTask$NewDirectOutputCollector\.<init>(MapTask\.java:521)
	at org\.apache\.hadoop\.mapred\.MapTask\.runNewMapper(MapTask\.java:636)
	at org\.apache\.hadoop\.mapred\.MapTask\.run(MapTask\.java:323)
	at org\.apache\.hadoop\.mapred\.Child$4\.run(Child\.java:270)
	at java\.security\.AccessController\.doPrivileged(Native Method)
	at javax\.security\.auth\.Subject\.doAs(Subject\.java:396)
	at org\.apache\.hadoop\.security\.UserGroupInformation\.doAs(UserGroupInformation\.java:1127)
	at org\.apache\.hadoop\.mapred\.Child\.main(Child\.java:264)
Caused by: org\.apache\.hadoop\.hbase\.TableNotFoundException: foobar
	at org\.apache\.hadoop\.hbase\.client\.HConnectionManager$HConnectionImplementation\.locateRegionInMeta(HConnectionManager\.java:724)
	at org\.apache\.hadoop\.hbase\.client\.HConnectionManager$HConnectionImplementation\.locateRegion(HConnectionManager\.java:593)
	at org\.apache\.hadoop\.hbase\.client\.HConnectionManager$HConnectionImplementation\.locateRegion(HConnectionManager\.java:558)
	at org\.apache\.hadoop\.hbase\.client\.HTable\.<init>(HTable\.java:172)
	at org\.apache\.hadoop\.hbase\.client\.HTable\.<init>(HTable\.java:146)
	at com\.cloudera\.sqoop\.hbase\.HBasePutProcessor\.setConf(HBasePutProcessor\.java:95)
	\.\.\. 12 more
" .
MapAttempt TASK_TYPE="MAP" TASKID="task_201109051946_0001_m_000001" TASK_ATTEMPT_ID="attempt_201109051946_0001_m_000001_0" START_TIME="1315245135674" TRACKER_NAME="tracker_nothing:localhost/127\.0\.0\.1:49420" HTTP_PORT="50060" .
MapAttempt TASK_TYPE="MAP" TASKID="task_201109051946_0001_m_000001" TASK_ATTEMPT_ID="attempt_201109051946_0001_m_000001_0" TASK_STATUS="FAILED" FINISH_TIME="1315245143534" HOSTNAME="nothing" ERROR="java\.lang\.RuntimeException: Could not access HBase table foobar
	at com\.cloudera\.sqoop\.hbase\.HBasePutProcessor\.setConf(HBasePutProcessor\.java:97)
	at org\.apache\.hadoop\.util\.ReflectionUtils\.setConf(ReflectionUtils\.java:62)
	at org\.apache\.hadoop\.util\.ReflectionUtils\.newInstance(ReflectionUtils\.java:117)
	at com\.cloudera\.sqoop\.mapreduce\.DelegatingOutputFormat$DelegatingRecordWriter\.<init>(DelegatingOutputFormat\.java:109)
	at com\.cloudera\.sqoop\.mapreduce\.DelegatingOutputFormat\.getRecordWriter(DelegatingOutputFormat\.java:84)
	at org\.apache\.hadoop\.mapred\.MapTask$NewDirectOutputCollector\.<init>(MapTask\.java:521)
	at org\.apache\.hadoop\.mapred\.MapTask\.runNewMapper(MapTask\.java:636)
	at org\.apache\.hadoop\.mapred\.MapTask\.run(MapTask\.java:323)
	at org\.apache\.hadoop\.mapred\.Child$4\.run(Child\.java:270)
	at java\.security\.AccessController\.doPrivileged(Native Method)
	at javax\.security\.auth\.Subject\.doAs(Subject\.java:396)
	at org\.apache\.hadoop\.security\.UserGroupInformation\.doAs(UserGroupInformation\.java:1127)
	at org\.apache\.hadoop\.mapred\.Child\.main(Child\.java:264)
Caused by: org\.apache\.hadoop\.hbase\.TableNotFoundException: foobar
	at org\.apache\.hadoop\.hbase\.client\.HConnectionManager$HConnectionImplementation\.locateRegionInMeta(HConnectionManager\.java:724)
	at org\.apache\.hadoop\.hbase\.client\.HConnectionManager$HConnectionImplementation\.locateRegion(HConnectionManager\.java:593)
	at org\.apache\.hadoop\.hbase\.client\.HConnectionManager$HConnectionImplementation\.locateRegion(HConnectionManager\.java:558)
	at org\.apache\.hadoop\.hbase\.client\.HTable\.<init>(HTable\.java:172)
	at org\.apache\.hadoop\.hbase\.client\.HTable\.<init>(HTable\.java:146)
	at com\.cloudera\.sqoop\.hbase\.HBasePutProcessor\.setConf(HBasePutProcessor\.java:95)
	\.\.\. 12 more
" .
MapAttempt TASK_TYPE="MAP" TASKID="task_201109051946_0001_m_000000" TASK_ATTEMPT_ID="attempt_201109051946_0001_m_000000_1" START_TIME="1315245143714" TRACKER_NAME="tracker_nothing:localhost/127\.0\.0\.1:49420" HTTP_PORT="50060" .
MapAttempt TASK_TYPE="MAP" TASKID="task_201109051946_0001_m_000000" TASK_ATTEMPT_ID="attempt_201109051946_0001_m_000000_1" TASK_STATUS="FAILED" FINISH_TIME="1315245151832" HOSTNAME="nothing" ERROR="java\.lang\.RuntimeException: Could not access HBase table foobar
	at com\.cloudera\.sqoop\.hbase\.HBasePutProcessor\.setConf(HBasePutProcessor\.java:97)
	at org\.apache\.hadoop\.util\.ReflectionUtils\.setConf(ReflectionUtils\.java:62)
	at org\.apache\.hadoop\.util\.ReflectionUtils\.newInstance(ReflectionUtils\.java:117)
	at com\.cloudera\.sqoop\.mapreduce\.DelegatingOutputFormat$DelegatingRecordWriter\.<init>(DelegatingOutputFormat\.java:109)
	at com\.cloudera\.sqoop\.mapreduce\.DelegatingOutputFormat\.getRecordWriter(DelegatingOutputFormat\.java:84)
	at org\.apache\.hadoop\.mapred\.MapTask$NewDirectOutputCollector\.<init>(MapTask\.java:521)
	at org\.apache\.hadoop\.mapred\.MapTask\.runNewMapper(MapTask\.java:636)
	at org\.apache\.hadoop\.mapred\.MapTask\.run(MapTask\.java:323)
	at org\.apache\.hadoop\.mapred\.Child$4\.run(Child\.java:270)
	at java\.security\.AccessController\.doPrivileged(Native Method)
	at javax\.security\.auth\.Subject\.doAs(Subject\.java:396)
	at org\.apache\.hadoop\.security\.UserGroupInformation\.doAs(UserGroupInformation\.java:1127)
	at org\.apache\.hadoop\.mapred\.Child\.main(Child\.java:264)
Caused by: org\.apache\.hadoop\.hbase\.TableNotFoundException: foobar
	at org\.apache\.hadoop\.hbase\.client\.HConnectionManager$HConnectionImplementation\.locateRegionInMeta(HConnectionManager\.java:724)
	at org\.apache\.hadoop\.hbase\.client\.HConnectionManager$HConnectionImplementation\.locateRegion(HConnectionManager\.java:593)
	at org\.apache\.hadoop\.hbase\.client\.HConnectionManager$HConnectionImplementation\.locateRegion(HConnectionManager\.java:558)
	at org\.apache\.hadoop\.hbase\.client\.HTable\.<init>(HTable\.java:172)
	at org\.apache\.hadoop\.hbase\.client\.HTable\.<init>(HTable\.java:146)
	at com\.cloudera\.sqoop\.hbase\.HBasePutProcessor\.setConf(HBasePutProcessor\.java:95)
	\.\.\. 12 more
" .
MapAttempt TASK_TYPE="MAP" TASKID="task_201109051946_0001_m_000001" TASK_ATTEMPT_ID="attempt_201109051946_0001_m_000001_1" START_TIME="1315245143716" TRACKER_NAME="tracker_nothing:localhost/127\.0\.0\.1:49420" HTTP_PORT="50060" .
MapAttempt TASK_TYPE="MAP" TASKID="task_201109051946_0001_m_000001" TASK_ATTEMPT_ID="attempt_201109051946_0001_m_000001_1" TASK_STATUS="FAILED" FINISH_TIME="1315245151977" HOSTNAME="nothing" ERROR="java\.lang\.RuntimeException: Could not access HBase table foobar
	at com\.cloudera\.sqoop\.hbase\.HBasePutProcessor\.setConf(HBasePutProcessor\.java:97)
	at org\.apache\.hadoop\.util\.ReflectionUtils\.setConf(ReflectionUtils\.java:62)
	at org\.apache\.hadoop\.util\.ReflectionUtils\.newInstance(ReflectionUtils\.java:117)
	at com\.cloudera\.sqoop\.mapreduce\.DelegatingOutputFormat$DelegatingRecordWriter\.<init>(DelegatingOutputFormat\.java:109)
	at com\.cloudera\.sqoop\.mapreduce\.DelegatingOutputFormat\.getRecordWriter(DelegatingOutputFormat\.java:84)
	at org\.apache\.hadoop\.mapred\.MapTask$NewDirectOutputCollector\.<init>(MapTask\.java:521)
	at org\.apache\.hadoop\.mapred\.MapTask\.runNewMapper(MapTask\.java:636)
	at org\.apache\.hadoop\.mapred\.MapTask\.run(MapTask\.java:323)
	at org\.apache\.hadoop\.mapred\.Child$4\.run(Child\.java:270)
	at java\.security\.AccessController\.doPrivileged(Native Method)
	at javax\.security\.auth\.Subject\.doAs(Subject\.java:396)
	at org\.apache\.hadoop\.security\.UserGroupInformation\.doAs(UserGroupInformation\.java:1127)
	at org\.apache\.hadoop\.mapred\.Child\.main(Child\.java:264)
Caused by: org\.apache\.hadoop\.hbase\.TableNotFoundException: foobar
	at org\.apache\.hadoop\.hbase\.client\.HConnectionManager$HConnectionImplementation\.locateRegionInMeta(HConnectionManager\.java:724)
	at org\.apache\.hadoop\.hbase\.client\.HConnectionManager$HConnectionImplementation\.locateRegion(HConnectionManager\.java:593)
	at org\.apache\.hadoop\.hbase\.client\.HConnectionManager$HConnectionImplementation\.locateRegion(HConnectionManager\.java:558)
	at org\.apache\.hadoop\.hbase\.client\.HTable\.<init>(HTable\.java:172)
	at org\.apache\.hadoop\.hbase\.client\.HTable\.<init>(HTable\.java:146)
	at com\.cloudera\.sqoop\.hbase\.HBasePutProcessor\.setConf(HBasePutProcessor\.java:95)
	\.\.\. 12 more
" .
MapAttempt TASK_TYPE="MAP" TASKID="task_201109051946_0001_m_000000" TASK_ATTEMPT_ID="attempt_201109051946_0001_m_000000_2" START_TIME="1315245152045" TRACKER_NAME="tracker_nothing:localhost/127\.0\.0\.1:49420" HTTP_PORT="50060" .
MapAttempt TASK_TYPE="MAP" TASKID="task_201109051946_0001_m_000000" TASK_ATTEMPT_ID="attempt_201109051946_0001_m_000000_2" TASK_STATUS="FAILED" FINISH_TIME="1315245159997" HOSTNAME="nothing" ERROR="java\.lang\.RuntimeException: Could not access HBase table foobar
	at com\.cloudera\.sqoop\.hbase\.HBasePutProcessor\.setConf(HBasePutProcessor\.java:97)
	at org\.apache\.hadoop\.util\.ReflectionUtils\.setConf(ReflectionUtils\.java:62)
	at org\.apache\.hadoop\.util\.ReflectionUtils\.newInstance(ReflectionUtils\.java:117)
	at com\.cloudera\.sqoop\.mapreduce\.DelegatingOutputFormat$DelegatingRecordWriter\.<init>(DelegatingOutputFormat\.java:109)
	at com\.cloudera\.sqoop\.mapreduce\.DelegatingOutputFormat\.getRecordWriter(DelegatingOutputFormat\.java:84)
	at org\.apache\.hadoop\.mapred\.MapTask$NewDirectOutputCollector\.<init>(MapTask\.java:521)
	at org\.apache\.hadoop\.mapred\.MapTask\.runNewMapper(MapTask\.java:636)
	at org\.apache\.hadoop\.mapred\.MapTask\.run(MapTask\.java:323)
	at org\.apache\.hadoop\.mapred\.Child$4\.run(Child\.java:270)
	at java\.security\.AccessController\.doPrivileged(Native Method)
	at javax\.security\.auth\.Subject\.doAs(Subject\.java:396)
	at org\.apache\.hadoop\.security\.UserGroupInformation\.doAs(UserGroupInformation\.java:1127)
	at org\.apache\.hadoop\.mapred\.Child\.main(Child\.java:264)
Caused by: org\.apache\.hadoop\.hbase\.TableNotFoundException: foobar
	at org\.apache\.hadoop\.hbase\.client\.HConnectionManager$HConnectionImplementation\.locateRegionInMeta(HConnectionManager\.java:724)
	at org\.apache\.hadoop\.hbase\.client\.HConnectionManager$HConnectionImplementation\.locateRegion(HConnectionManager\.java:593)
	at org\.apache\.hadoop\.hbase\.client\.HConnectionManager$HConnectionImplementation\.locateRegion(HConnectionManager\.java:558)
	at org\.apache\.hadoop\.hbase\.client\.HTable\.<init>(HTable\.java:172)
	at org\.apache\.hadoop\.hbase\.client\.HTable\.<init>(HTable\.java:146)
	at com\.cloudera\.sqoop\.hbase\.HBasePutProcessor\.setConf(HBasePutProcessor\.java:95)
	\.\.\. 12 more
" .
MapAttempt TASK_TYPE="MAP" TASKID="task_201109051946_0001_m_000001" TASK_ATTEMPT_ID="attempt_201109051946_0001_m_000001_2" START_TIME="1315245152046" TRACKER_NAME="tracker_nothing:localhost/127\.0\.0\.1:49420" HTTP_PORT="50060" .
MapAttempt TASK_TYPE="MAP" TASKID="task_201109051946_0001_m_000001" TASK_ATTEMPT_ID="attempt_201109051946_0001_m_000001_2" TASK_STATUS="FAILED" FINISH_TIME="1315245160006" HOSTNAME="nothing" ERROR="java\.lang\.RuntimeException: Could not access HBase table foobar
	at com\.cloudera\.sqoop\.hbase\.HBasePutProcessor\.setConf(HBasePutProcessor\.java:97)
	at org\.apache\.hadoop\.util\.ReflectionUtils\.setConf(ReflectionUtils\.java:62)
	at org\.apache\.hadoop\.util\.ReflectionUtils\.newInstance(ReflectionUtils\.java:117)
	at com\.cloudera\.sqoop\.mapreduce\.DelegatingOutputFormat$DelegatingRecordWriter\.<init>(DelegatingOutputFormat\.java:109)
	at com\.cloudera\.sqoop\.mapreduce\.DelegatingOutputFormat\.getRecordWriter(DelegatingOutputFormat\.java:84)
	at org\.apache\.hadoop\.mapred\.MapTask$NewDirectOutputCollector\.<init>(MapTask\.java:521)
	at org\.apache\.hadoop\.mapred\.MapTask\.runNewMapper(MapTask\.java:636)
	at org\.apache\.hadoop\.mapred\.MapTask\.run(MapTask\.java:323)
	at org\.apache\.hadoop\.mapred\.Child$4\.run(Child\.java:270)
	at java\.security\.AccessController\.doPrivileged(Native Method)
	at javax\.security\.auth\.Subject\.doAs(Subject\.java:396)
	at org\.apache\.hadoop\.security\.UserGroupInformation\.doAs(UserGroupInformation\.java:1127)
	at org\.apache\.hadoop\.mapred\.Child\.main(Child\.java:264)
Caused by: org\.apache\.hadoop\.hbase\.TableNotFoundException: foobar
	at org\.apache\.hadoop\.hbase\.client\.HConnectionManager$HConnectionImplementation\.locateRegionInMeta(HConnectionManager\.java:724)
	at org\.apache\.hadoop\.hbase\.client\.HConnectionManager$HConnectionImplementation\.locateRegion(HConnectionManager\.java:593)
	at org\.apache\.hadoop\.hbase\.client\.HConnectionManager$HConnectionImplementation\.locateRegion(HConnectionManager\.java:558)
	at org\.apache\.hadoop\.hbase\.client\.HTable\.<init>(HTable\.java:172)
	at org\.apache\.hadoop\.hbase\.client\.HTable\.<init>(HTable\.java:146)
	at com\.cloudera\.sqoop\.hbase\.HBasePutProcessor\.setConf(HBasePutProcessor\.java:95)
	\.\.\. 12 more
" .
MapAttempt TASK_TYPE="MAP" TASKID="task_201109051946_0001_m_000000" TASK_ATTEMPT_ID="attempt_201109051946_0001_m_000000_3" START_TIME="1315245160025" TRACKER_NAME="tracker_nothing:localhost/127\.0\.0\.1:49420" HTTP_PORT="50060" .
MapAttempt TASK_TYPE="MAP" TASKID="task_201109051946_0001_m_000000" TASK_ATTEMPT_ID="attempt_201109051946_0001_m_000000_3" TASK_STATUS="FAILED" FINISH_TIME="1315245167979" HOSTNAME="nothing" ERROR="java\.lang\.RuntimeException: Could not access HBase table foobar
	at com\.cloudera\.sqoop\.hbase\.HBasePutProcessor\.setConf(HBasePutProcessor\.java:97)
	at org\.apache\.hadoop\.util\.ReflectionUtils\.setConf(ReflectionUtils\.java:62)
	at org\.apache\.hadoop\.util\.ReflectionUtils\.newInstance(ReflectionUtils\.java:117)
	at com\.cloudera\.sqoop\.mapreduce\.DelegatingOutputFormat$DelegatingRecordWriter\.<init>(DelegatingOutputFormat\.java:109)
	at com\.cloudera\.sqoop\.mapreduce\.DelegatingOutputFormat\.getRecordWriter(DelegatingOutputFormat\.java:84)
	at org\.apache\.hadoop\.mapred\.MapTask$NewDirectOutputCollector\.<init>(MapTask\.java:521)
	at org\.apache\.hadoop\.mapred\.MapTask\.runNewMapper(MapTask\.java:636)
	at org\.apache\.hadoop\.mapred\.MapTask\.run(MapTask\.java:323)
	at org\.apache\.hadoop\.mapred\.Child$4\.run(Child\.java:270)
	at java\.security\.AccessController\.doPrivileged(Native Method)
	at javax\.security\.auth\.Subject\.doAs(Subject\.java:396)
	at org\.apache\.hadoop\.security\.UserGroupInformation\.doAs(UserGroupInformation\.java:1127)
	at org\.apache\.hadoop\.mapred\.Child\.main(Child\.java:264)
Caused by: org\.apache\.hadoop\.hbase\.TableNotFoundException: foobar
	at org\.apache\.hadoop\.hbase\.client\.HConnectionManager$HConnectionImplementation\.locateRegionInMeta(HConnectionManager\.java:724)
	at org\.apache\.hadoop\.hbase\.client\.HConnectionManager$HConnectionImplementation\.locateRegion(HConnectionManager\.java:593)
	at org\.apache\.hadoop\.hbase\.client\.HConnectionManager$HConnectionImplementation\.locateRegion(HConnectionManager\.java:558)
	at org\.apache\.hadoop\.hbase\.client\.HTable\.<init>(HTable\.java:172)
	at org\.apache\.hadoop\.hbase\.client\.HTable\.<init>(HTable\.java:146)
	at com\.cloudera\.sqoop\.hbase\.HBasePutProcessor\.setConf(HBasePutProcessor\.java:95)
	\.\.\. 12 more
" .
Task TASKID="task_201109051946_0001_m_000000" TASK_TYPE="MAP" TASK_STATUS="FAILED" FINISH_TIME="1315245167979" ERROR="java\.lang\.RuntimeException: Could not access HBase table foobar
	at com\.cloudera\.sqoop\.hbase\.HBasePutProcessor\.setConf(HBasePutProcessor\.java:97)
	at org\.apache\.hadoop\.util\.ReflectionUtils\.setConf(ReflectionUtils\.java:62)
	at org\.apache\.hadoop\.util\.ReflectionUtils\.newInstance(ReflectionUtils\.java:117)
	at com\.cloudera\.sqoop\.mapreduce\.DelegatingOutputFormat$DelegatingRecordWriter\.<init>(DelegatingOutputFormat\.java:109)
	at com\.cloudera\.sqoop\.mapreduce\.DelegatingOutputFormat\.getRecordWriter(DelegatingOutputFormat\.java:84)
	at org\.apache\.hadoop\.mapred\.MapTask$NewDirectOutputCollector\.<init>(MapTask\.java:521)
	at org\.apache\.hadoop\.mapred\.MapTask\.runNewMapper(MapTask\.java:636)
	at org\.apache\.hadoop\.mapred\.MapTask\.run(MapTask\.java:323)
	at org\.apache\.hadoop\.mapred\.Child$4\.run(Child\.java:270)
	at java\.security\.AccessController\.doPrivileged(Native Method)
	at javax\.security\.auth\.Subject\.doAs(Subject\.java:396)
	at org\.apache\.hadoop\.security\.UserGroupInformation\.doAs(UserGroupInformation\.java:1127)
	at org\.apache\.hadoop\.mapred\.Child\.main(Child\.java:264)
Caused by: org\.apache\.hadoop\.hbase\.TableNotFoundException: foobar
	at org\.apache\.hadoop\.hbase\.client\.HConnectionManager$HConnectionImplementation\.locateRegionInMeta(HConnectionManager\.java:724)
	at org\.apache\.hadoop\.hbase\.client\.HConnectionManager$HConnectionImplementation\.locateRegion(HConnectionManager\.java:593)
	at org\.apache\.hadoop\.hbase\.client\.HConnectionManager$HConnectionImplementation\.locateRegion(HConnectionManager\.java:558)
	at org\.apache\.hadoop\.hbase\.client\.HTable\.<init>(HTable\.java:172)
	at org\.apache\.hadoop\.hbase\.client\.HTable\.<init>(HTable\.java:146)
	at com\.cloudera\.sqoop\.hbase\.HBasePutProcessor\.setConf(HBasePutProcessor\.java:95)
	\.\.\. 12 more
" TASK_ATTEMPT_ID="" .
MapAttempt TASK_TYPE="MAP" TASKID="task_201109051946_0001_m_000001" TASK_ATTEMPT_ID="attempt_201109051946_0001_m_000001_3" START_TIME="1315245160027" TRACKER_NAME="tracker_nothing:localhost/127\.0\.0\.1:49420" HTTP_PORT="50060" .
MapAttempt TASK_TYPE="MAP" TASKID="task_201109051946_0001_m_000001" TASK_ATTEMPT_ID="attempt_201109051946_0001_m_000001_3" TASK_STATUS="FAILED" FINISH_TIME="1315245167979" HOSTNAME="nothing" ERROR="java\.lang\.RuntimeException: Could not access HBase table foobar
	at com\.cloudera\.sqoop\.hbase\.HBasePutProcessor\.setConf(HBasePutProcessor\.java:97)
	at org\.apache\.hadoop\.util\.ReflectionUtils\.setConf(ReflectionUtils\.java:62)
	at org\.apache\.hadoop\.util\.ReflectionUtils\.newInstance(ReflectionUtils\.java:117)
	at com\.cloudera\.sqoop\.mapreduce\.DelegatingOutputFormat$DelegatingRecordWriter\.<init>(DelegatingOutputFormat\.java:109)
	at com\.cloudera\.sqoop\.mapreduce\.DelegatingOutputFormat\.getRecordWriter(DelegatingOutputFormat\.java:84)
	at org\.apache\.hadoop\.mapred\.MapTask$NewDirectOutputCollector\.<init>(MapTask\.java:521)
	at org\.apache\.hadoop\.mapred\.MapTask\.runNewMapper(MapTask\.java:636)
	at org\.apache\.hadoop\.mapred\.MapTask\.run(MapTask\.java:323)
	at org\.apache\.hadoop\.mapred\.Child$4\.run(Child\.java:270)
	at java\.security\.AccessController\.doPrivileged(Native Method)
	at javax\.security\.auth\.Subject\.doAs(Subject\.java:396)
	at org\.apache\.hadoop\.security\.UserGroupInformation\.doAs(UserGroupInformation\.java:1127)
	at org\.apache\.hadoop\.mapred\.Child\.main(Child\.java:264)
Caused by: org\.apache\.hadoop\.hbase\.TableNotFoundException: foobar
	at org\.apache\.hadoop\.hbase\.client\.HConnectionManager$HConnectionImplementation\.locateRegionInMeta(HConnectionManager\.java:724)
	at org\.apache\.hadoop\.hbase\.client\.HConnectionManager$HConnectionImplementation\.locateRegion(HConnectionManager\.java:593)
	at org\.apache\.hadoop\.hbase\.client\.HConnectionManager$HConnectionImplementation\.locateRegion(HConnectionManager\.java:558)
	at org\.apache\.hadoop\.hbase\.client\.HTable\.<init>(HTable\.java:172)
	at org\.apache\.hadoop\.hbase\.client\.HTable\.<init>(HTable\.java:146)
	at com\.cloudera\.sqoop\.hbase\.HBasePutProcessor\.setConf(HBasePutProcessor\.java:95)
	\.\.\. 12 more
" .
Task TASKID="task_201109051946_0001_m_000003" TASK_TYPE="CLEANUP" START_TIME="1315245167986" SPLITS="" .
MapAttempt TASK_TYPE="CLEANUP" TASKID="task_201109051946_0001_m_000003" TASK_ATTEMPT_ID="attempt_201109051946_0001_m_000003_0" START_TIME="1315245167990" TRACKER_NAME="tracker_nothing:localhost/127\.0\.0\.1:49420" HTTP_PORT="50060" .
MapAttempt TASK_TYPE="CLEANUP" TASKID="task_201109051946_0001_m_000003" TASK_ATTEMPT_ID="attempt_201109051946_0001_m_000003_0" TASK_STATUS="SUCCESS" FINISH_TIME="1315245169632" HOSTNAME="/default-rack/nothing" STATE_STRING="cleanup" COUNTERS="{(FileSystemCounters)(FileSystemCounters)[(FILE_BYTES_WRITTEN)(FILE_BYTES_WRITTEN)(82264)]}{(org\.apache\.hadoop\.mapred\.Task$Counter)(Map-Reduce Framework)[(SPILLED_RECORDS)(Spilled Records)(0)]}" .
Task TASKID="task_201109051946_0001_m_000003" TASK_TYPE="CLEANUP" TASK_STATUS="SUCCESS" FINISH_TIME="1315245169813" COUNTERS="{(FileSystemCounters)(FileSystemCounters)[(FILE_BYTES_WRITTEN)(FILE_BYTES_WRITTEN)(82264)]}{(org\.apache\.hadoop\.mapred\.Task$Counter)(Map-Reduce Framework)[(SPILLED_RECORDS)(Spilled Records)(0)]}" .
Job JOBID="job_201109051946_0001" FINISH_TIME="1315245169813" JOB_STATUS="FAILED" FINISHED_MAPS="0" FINISHED_REDUCES="0" .
